### ISSUE TITLE
default commit message subject change proposal to make compatible with commitlint

### ISSUE THREAD

**Issue by xmlking** [semantic-release/git#82] opened 2018-09-09 19:57 UTC
to fix issue: https://github.com/semantic-release/semantic-release/issues/928
can we change default commit message subject  to 

```json
"message": "chore(release): version ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
```

from 
```json
"message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
```

**Comment by pvdlg** [comment] 2018-09-10 15:22
Duplicate of semantic-release/semantic-release#928

**Closed by pvdlg** 2018-09-10 15:22 UTC
