### ISSUE TITLE
GPG Signatures Configuration

### ISSUE THREAD

**Issue by AliSajid** [semantic-release/git#438] opened 2023-04-14 14:03 UTC
Hi,

I am trying to set up GPG signing for all my commits, including those by semantic-release. I use github actions for CI. I wanted to know if the plugin picks up the gpg signature settings automatically from the environment or do I need to explicitly modify Git Configuration during the CI run.

If there's no automatic detection, would it be possible for you to entertain a pull request that does that?

**Comment by 0x464e** [comment] 2023-07-21 17:59
Did you get this solved?  
I'm also looking to have my release commit signed when using GitHub actions.

**Comment by travi** [comment] 2023-07-21 19:03
https://github.com/semantic-release/git#gpg-signature

**Comment by 0x464e** [comment] 2023-07-22 17:20
> https://github.com/semantic-release/git#gpg-signature

Not sure I'm stupid or you understood the question wrong, but that is about Travis, not GitHub Actions.  
Anyway, I managed to get it working (after way too much struggle) by following this:  
https://gist.github.com/vansergen/88eb7e71fea2e3bdaf6aa3e752371eb7

**Comment by 0x464e** [comment] 2023-07-22 17:26
Also while I have you here and you might see these messages @travi, any Idea why using a simple workflow like this didn't work with `semantic-release`?  
https://github.com/crazy-max/ghaction-import-gpg

The `semantic-release` workflow just froze indefinitely (until I clicked cancel) after completing the release note generation step.  
And I can confirm I set up that `import gpg` workflow correctly, because it worked and signed my commits just fine when I tried things other than `semantic-release`.

If you have no idea to throw from on top of your head, that's fine. I can make an issue in some repo (not sure where I should make it), or just let the problem be. I'm also fine with my manual signing setup.

**Comment by seebeen** [comment] 2023-08-10 07:57
Heya,

That action works, and commits are signed. You can see that here: https://github.com/oblakstudio/extremis-core/commits/master

Here is the workflow that GPG signs everything.
Note the commiter config in the release step, and see the specific GPG config
https://github.com/oblakstudio/extremis-core/blob/master/.github/workflows/release.yml

**Comment by 0x464e** [comment] 2023-08-10 14:33
Interesting, because (if I remember correctly) I set up everything just like you did, but it just would not work.  
Might give it a second try, but for now I'm just manually setting up gpg for signing commits (see https://github.com/0x464e/slideshow-video/blob/master/.github/workflows/release.yml)

**Comment by seebeen** [comment] 2023-08-10 14:48
If you're doing the release as yourself, you can copy the parts from my config regarding the GPG action.
If your commiter config in the release step matches (BOTH name and email) - everything should be signed.

Give it a go, and if it doesn't work, I'll take a look and make a PR :)

**Comment by sheerlox** [comment] 2023-11-22 21:12
@0x464e 

> The semantic-release workflow just froze indefinitely (until I clicked cancel) after completing the release note generation step.

> Interesting, because (if I remember correctly) I set up everything just like you did, but it just would not work.

I ran into this issue as well a few days ago. After investigation (notably turning `execa` debug mode on), the issue was coming from git trying to sign the tag. As lightweight tags cannot be signed, it automatically tries to make an annotated tag, which needs a message. For this reason, an editor is raised, hanging the process indefinitely.

The issue is in `semantic-release` and not its `git` plugin (which got me at first too), I've opened an issue there.

Let's track this here: https://github.com/semantic-release/semantic-release/issues/3065

---

Since the original issue was resolved [by Matt's response](https://github.com/semantic-release/git/issues/438#issuecomment-1646129574) and [the Gist shared by 0x464e](https://gist.github.com/vansergen/88eb7e71fea2e3bdaf6aa3e752371eb7), I'm closing this issue.

**Closed by sheerlox** 2023-11-22 21:12 UTC
