### ISSUE TITLE
tagFormat is giving error

### ISSUE THREAD

**Issue by avinash8526** [semantic-release/git#78] opened 2018-08-28 14:42 UTC
I have `.releaserc` file which have tagformat as `  "tagFormat":"v${version}-${branch}" `
everytime I run semantic release I get branch is `ReferenceError: branch is not defined`

Branch is set as env variable
`
An error occurred while running semantic-release: ReferenceError: branch is not defined
    at eval (lodash.templateSources[0]:11:10)
    at module.exports (/Users/avinash/nukeland/alien-release/node_modules/semantic-release/lib/verify.js:16:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ReferenceError: branch is not defined
    at eval (lodash.templateSources[0]:11:10)
    at module.exports (/Users/avinash/nukeland/alien-release/node_modules/semantic-release/lib/verify.js:16:48)
`

`➜  alien-release git:(master) ✗ printenv | grep branch
branch=master
`

**Comment by pvdlg** [comment] 2018-08-28 15:30
The only variable passed by semantic-release to the template is `version`. As indicated by the error message the `branch` variable doesn't exists.

As semantic-release support only one entry for the `branch` option it doesn't make sense to use a variable here. You might rather set the branch name directly in the tag format (`v${version}-my-branch`) or omit it as it doesn't bring much value considering all releases would be done from the same branch anyway.

If you still want to use a variable and if you have set an environment variable, in Javascript you can access it `process.env.BRANCH` (if the variable is named `BRANCH`): `v${version}-${process.env.BRANCH}`.

**Comment by avinash8526** [comment] 2018-08-29 05:53
@pvdlg Thanks for quickly responding. 1st of all hats off for making this awesome plugin.
Now coming to the context. In our organisation we do release from patch branch and dev branch . (as we are startup) hence the problem I faced in my POC is that when I released from dev branch I got the version as `0.4.0` and my master was at 0.3.1
Now when I made another release from master I got tag as 0.4.0  which was already existing and hence semantic-release failed.

I will try the option suggested by you. Meanwhile here is my POC repository 
https://github.com/avinash8526/alien-release/blob/master/docs/changelog.md

**Comment by pvdlg** [comment] 2018-08-29 14:02
What are trying cannot work because release must have a unique version number, independently of the branch they were released from. It seems you are trying to workaround that by adding the branch to the tag to make it unique, but that won't work for GitHub release, npm or any package manager you might use.
Basically what you are trying to do would result in two `0.4.0` release with different code, which is fundamentally "wrong", so any package manager would prevent that.
You might be interested in https://github.com/semantic-release/semantic-release/issues/563 though.

**Comment by pvdlg** [comment] 2018-09-04 17:18
Closing as the functionality works as designed

**Closed by pvdlg** 2018-09-04 17:18 UTC
Labels: core, support
