### ISSUE TITLE
An error occurred while running semantic-release: Error: You provided a local path

### ISSUE THREAD

**Issue by fsilveira** [semantic-release/git#90] opened 2018-10-24 14:34 UTC
I get this error when I run: npx semantic-release

> [12:02:07] [semantic-release] › ℹ  Running semantic-release version 15.10.5
[12:02:07] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[12:02:07] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[12:02:07] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[12:02:08] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
[12:02:08] [semantic-release] › ℹ  This run was not triggered in a known CI environment, running in dry-run mode.
[12:02:08] [semantic-release] › ✔  Run automated release from branch master
[12:02:08] [semantic-release] › ✖  An error occurred while running semantic-release: Error: You provided a local path.
    at parseUrl (/home/fernando/.nvm/versions/node/v8.12.0/lib/node_modules/semantic-release/node_modules/parse-url/lib/index.js:48:15)
    at gitUp (/home/fernando/.nvm/versions/node/v8.12.0/lib/node_modules/semantic-release/node_modules/git-up/lib/index.js:29:18)
    at gitUrlParse (/home/fernando/.nvm/versions/node/v8.12.0/lib/node_modules/semantic-release/node_modules/git-url-parse/lib/index.js:42:19)
    at module.exports (/home/fernando/.nvm/versions/node/v8.12.0/lib/node_modules/semantic-release/lib/get-git-auth-url.js:49:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Error: You provided a local path.
    at parseUrl (/home/fernando/.nvm/versions/node/v8.12.0/lib/node_modules/semantic-release/node_modules/parse-url/lib/index.js:48:15)
    at gitUp (/home/fernando/.nvm/versions/node/v8.12.0/lib/node_modules/semantic-release/node_modules/git-up/lib/index.js:29:18)
    at gitUrlParse (/home/fernando/.nvm/versions/node/v8.12.0/lib/node_modules/semantic-release/node_modules/git-url-parse/lib/index.js:42:19)
    at module.exports (/home/fernando/.nvm/versions/node/v8.12.0/lib/node_modules/semantic-release/lib/get-git-auth-url.js:49:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)%

**Comment by pvdlg** [comment] 2018-10-24 16:09
Duplicate of semantic-release/semantic-release#963

**Closed by pvdlg** 2018-10-24 16:09 UTC
