### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by rap2hpoutre** [semantic-release/git#194] opened 2020-02-17 15:18 UTC
Running semantic release with latest version of `@semantic-release/git`

```
[3:16:01 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Cannot read property 'name' of undefined
    at module.exports (/home/travis/build/ForestAdmin/forest-express/node_modules/@semantic-release/git/lib/prepare.js:69:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async prepare (/home/travis/build/ForestAdmin/forest-express/node_modules/@semantic-release/git/index.js:28:3)
    at async validator (/home/travis/build/ForestAdmin/forest-express/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/travis/build/ForestAdmin/forest-express/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/home/travis/build/ForestAdmin/forest-express/node_modules/p-reduce/index.js:16:18) {
  pluginName: '@semantic-release/git'
}
TypeError: Cannot read property 'name' of undefined
    at module.exports (/home/travis/build/ForestAdmin/forest-express/node_modules/@semantic-release/git/lib/prepare.js:69:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async prepare (/home/travis/build/ForestAdmin/forest-express/node_modules/@semantic-release/git/index.js:28:3)
    at async validator (/home/travis/build/ForestAdmin/forest-express/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/travis/build/ForestAdmin/forest-express/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/home/travis/build/ForestAdmin/forest-express/node_modules/p-reduce/index.js:16:18) {
  pluginName: '@semantic-release/git'
```

**Comment by pvdlg** [comment] 2020-02-17 18:18
Duplicate of #185

**Comment by pvdlg** [comment] 2020-02-17 18:19
See https://github.com/semantic-release/git/issues/185#issuecomment-573209765 for the solution.

Please remember to search in the issue tracker to see if similar issue already exists.

**Closed by pvdlg** 2020-02-17 18:18 UTC
