### ISSUE TITLE
Error: Command failed: git fetch --tags

### ISSUE THREAD

**Issue by moltar** [semantic-release/git#136] opened 2019-04-20 08:21 UTC
The issue happens with tags that change their pointer.

```
❯ git fetch --tags
From gitlab.com:foo/repo
 ! [rejected]        flux-sync  -> flux-sync  (would clobber existing tag)

❯ git fetch --tags -f
From gitlab.com:foo/repo
 t [tag update]      flux-sync  -> flux-sync
```

Basically need to add `-f`, if it's safe globally, or maybe a config option.

Thanks!

**Comment by pvdlg** [comment] 2019-06-05 18:54
Can you provide more details. How do you end up in that situation.
Please provide steps to reproduce.

**Comment by moltar** [comment] 2019-06-05 20:47
Flux is a K8s GitOps tool.

It updates the tag to point to the latest release.

So basically just updating a tag to point to a new HEAD is the repro.

**Comment by pvdlg** [comment] 2019-06-12 16:29
I still have no idea how this related to semantic-release not how to reproduce.
I can't help you if on't provide more details and reproduction steps.

**Comment by moltar** [comment] 2019-06-12 17:39
Hi Pierre,

Unfortunately, I cannot create a test environment by hand to reproduce this.

But essentially, what happened is the following.

A third party service force-updates an existing tag, which now points to a different commit than before. This tag was already published.

When `semantic-release/git` fetches the tags from remote without the `-f` flag, the error is thrown and the fetch fails.

A way to reproduce would be:

1. Make a successful release
2. Add a new tag `git tag foo`
3. Create another release later
4. Update a tag `git tag -f foo` <-- now points to a different ref
5. Try to release and it will fail

**Comment by pvdlg** [comment] 2019-06-12 17:49
You shouldn't modify the commits release tags points to. That would completely mess up what semantic-release is doing. semantic-releases uses those tags to figure out what are the new commits since the last release, so if you change those the releases won't happens as intended.

In addition this error is due to the fact that you have a discrepancy between the tags on the remote and the local repo. semantic-release should run on your CI on a freshly cloned repo in which case you shouldn't have discrepancy between the remote and the clone.

I don't know what is your current workflow, but it seems to be something we can't support.

Even if we were to add `-f` to `git fetch --tags` that would only remove this error message but wouldn't solve the core issue: you should never change release tags, and your local repo clone should be identical to the remote.

**Comment by moltar** [comment] 2019-06-12 17:54
I am not modifying the semantic release tags though. My example has a `foo` tag. Real world example was a `flux-sync` tag.

**Comment by pvdlg** [comment] 2019-06-12 17:56
Still the problem is you have a discrepancy between your remote and your local repo.
How does that happened?
How do you clone your local repo on the CI?

**Comment by pvdlg** [comment] 2019-08-09 18:32
Closing as no answer provided

**Closed by pvdlg** 2019-08-09 18:32 UTC
Labels: info requested

**Comment by manjupriyajaintm** [comment] 2019-09-05 14:38
Hello community, I just found myself with this problem too, but I just solved it.

Surely when running the "react-native upgrade" command, it gave them the message that it was not necessary to update or with the command "react-native eject" that the command is not recognized.

Now you should use the "**react-native upgrade --legacy true**" command to back up your android folders or ios as the case may be as this command will replace your files.

Now it's just telling you not to replace your package.json

Greetings.

**Comment by demisx** [comment] 2019-09-24 20:31
I am having the same issue as @moltar. Once flux updates the remote tag `flux-sync-prod` after the repo has been already cloned by CI, the semantic-release command `git fetch --tags [repositoryUrl]` fails to update it with this message (see below). Perhaps the git command is missing  the `--force` flag?

```
[8:17:54 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: git fetch --tags https://gitlab-ci-token:[secure]@[repositoryUrl]
From https://git.[redacted]:
 * branch              HEAD           -> FETCH_HEAD
 ! [rejected]          flux-sync-prod -> flux-sync-prod  (would clobber existing tag)
```

**Comment by demisx** [comment] 2019-09-24 23:25
Just to clarify, I meant addition of this `--force` flag here: https://github.com/semantic-release/semantic-release/compare/master...beocommedia:force-local-tag-updates.

Not sure if doing so makes sense for everyone. For now, I am just running these on CI before invoking `npx semantic-release ...` and right before publishing to GitLab. This is not perfect, but minimizes chances of flux repo updates interfering with the `semantic-release` updates.

```
git fetch -tp -f --all
git tag -d flux-sync-stg || true
git tag -d flux-sync-prod || true
```
