### ISSUE TITLE
`git ls-files -m -o` fails when upgrading from v5

### ISSUE THREAD

**Issue by mattyclarkson** [semantic-release/git#62] opened 2018-07-17 08:28 UTC
After upgrading I get a error when listing modified files. I assume this might be something to do with the assets change but not sure the correct way to fix it. The build requires no extra assets other than the `package.json` and `CHANGELOG.md`. I cannot reproduce it locally, so not sure what is happening. My hunch is that CircleCI is somehow enabling the modules inside the `node_modules` was wondering if you peeps have a better idea. See the [build][build] failure and the [project][project]

```
[Semantic release]: An error occurred while running semantic-release: { Error: Command failed: git ls-files -m -o
fatal: Not a git repository: node_modules/art/lib/slick/../../.git/modules/lib/slick


    at makeError (/home/circleci/repo/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/home/circleci/repo/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 128,
  stdout: '',
  stderr: 'fatal: Not a git repository: node_modules/art/lib/slick/../../.git/modules/lib/slick\n',
  failed: true,
  signal: null,
  cmd: 'git ls-files -m -o',
  timedOut: false,
  killed: false,
  pluginName: '@semantic-release/git' }
```

Have just stuck with v5 for now...

[build]: https://circleci.com/gh/ef-carbon/react-native-chat/768
[project]: https://github.com/ef-carbon/react-native-chat

**Comment by pvdlg** [comment] 2018-07-17 14:46
It seems to be related to your dependency to https://github.com/sebmarkbage/art.
The npm package contains a [.gitmodules](https://github.com/sebmarkbage/art/blob/master/.gitmodules) that seems to refer to directories that are not present.
However I cannot reproduce locally with git version 2.18.0. Maybe the version installed in CircleCI is older and behave differently with submodule.
Can you confirm the git version on CircleCI?

**Comment by mattyclarkson** [comment] 2018-07-17 14:49
It's pretty old...

```
circleci@build:~$ git --version
git version 2.1.4
```

That's prolly why I couldn't repro locally either

**Comment by pvdlg** [comment] 2018-07-17 14:56
I can confirm that I get the same error locally with git 2.1.4.
I'm not sure how to solve the problem yet...

**Comment by pvdlg** [comment] 2018-07-17 15:39
It seems this was fixed in Git 2.7.1.
The problem is mostly with https://github.com/sebmarkbage/art that includes a `.gitmodules` in it's npm package which reference a directory that is not a git repo.

I tried to find a way to run `git ls-files -m -o` without reading `.gitmodules` files but it doesn't seems to be possible in version < 2.7.1.

Another solution is to always exclude some directory such as `node_modules`. But that's not really a good fix as you can always have any directory containing a `.gitmodules` pointing to a directory that doesn't exists.

**Comment by pvdlg** [comment] 2018-07-17 15:41
Maybe you can ask the own of https://github.com/sebmarkbage/art to add `.gitmodules` to https://github.com/sebmarkbage/art/blob/master/.npmignore?

**Comment by mattyclarkson** [comment] 2018-07-17 15:41
I can ping CircleCI to update the version of git in their Docker image. I *could* workaround it by doing something like `find node_modules -type d --name .gitmodule -exec rm -r '{}' \;` as a post install step.

**Comment by mattyclarkson** [comment] 2018-07-17 15:42
There are multiple `node_modules` that have `.gitmodules` in them. I can start doing the upstream issues though.

**Comment by pvdlg** [comment] 2018-07-17 15:44
Ideally I'd like to find a way to prevent the issue in this module. 
If you have any idea on how to run `git ls-files -m -o` ignoring `.gitmodules` let me know.

**Comment by pvdlg** [comment] 2018-07-17 15:48
It seems using the option `--directory` solve the problem. I have to check if it doesn't have any negative impact.

**Comment by pvdlg** [comment] 2018-07-17 18:15
I think I have a solution but it's going to take me some more time to implement it.

Currently we get the files that got modified, and then we determine which one match a glob in `asset`.
My solution would do it the other way around:
1. Glob the `assets`
2. Filter the matches to keep only the ones that has been modified
3. Commit that list

**Closed** 2018-07-19 04:10 UTC
Labels: feature, plugin:git
