### ISSUE TITLE
release 5.0.0 has no defaults

### ISSUE THREAD

**Issue by AVVS** [semantic-release/git#48] opened 2018-05-09 19:13 UTC
on top of the breaking change this actually has no defaults (in contrary to the readme)
please return the defaults as they are extremely useful where system is running without default git configuration (ie semaphore CI), ie:

```sh
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'runner@semaphore-1802.(none)')
```

**Comment by gr2m** [comment] 2018-05-09 20:26
Hey @AVVS we are both occupied by other things right now. If you could look into it and send a PR with tests we could get this handled quickly, otherwise it might take until end of May

**Comment by pvdlg** [comment] 2018-05-09 20:48
This has been changed to solve #36.
The goal is to not change the config anymore. And it make sense that running semantic-release shouldn’t modify your repo config.
This is why in 5.0.0 we use the git environment variable. And we do default them.

What version of semantic-release are you using?

**Comment by AVVS** [comment] 2018-05-09 21:32
15.x.x something

Generally what I'm suggesting is setting env variables for producing that specific commit in case they are not already present. That would avoid the issue you've mentioned while making sure its atill usable without extra effort on setting up the commiter

**Comment by pvdlg** [comment] 2018-05-09 21:51
That’s exactly what we do in version 15.4.0

What is the exact version you are using?

**Comment by AVVS** [comment] 2018-05-09 21:53
[Semantic release]: Running semantic-release version 15.1.5 - so definitely could be an issue in that, I guess, I'll try with the updated one

**Comment by pvdlg** [comment] 2018-05-09 21:56
You should have a warning during the installation as the git plugin has a peer dependency to semantic-release 15.4.0 or higher

**Comment by pvdlg** [comment] 2018-05-15 13:28
Closing as is seems the problem was due to an outdated version of semantic-release.
Please re-open if the problem is not solved.

**Closed by pvdlg** 2018-05-15 13:28 UTC
